### ISSUE TITLE
Use only one URL for 'url'

### ISSUE THREAD

**Issue by bellerophons-pegasus** [acdh-oeaw/arche-biblatex#4]
Currently, thee BibLaTeX service promotes all available URLs to `biblatex url`

So for https://hdl.handle.net/21.11115/0000-000D-FEAB-5 we get 
```url = {https://arche.acdh.oeaw.ac.at/api/109678, https://hdl.handle.net/21.11115/0000-000D-FEAB-5, https://id.acdh.oeaw.ac.at/rita, https://hdl.handle.net/21.11115/0000-000D-FEAB-5},```

bibtex/biber etc. can only handle one URL. Thus, we also only want to have one. We already have a rule in place to chose the 'best' URL for a recource: it is the one behind 'Copy Resource Link' (@nczirjak-acdh can help out here)

So when that rue is applied the example above should render:
``` 
url = {https://hdl.handle.net/21.11115/0000-000D-FEAB-5},
```

**Comment by zozlak** [comment]
Undestood. Will implement it no later than mid next week.

**Comment by zozlak** [comment]
Solved by 2be1cefde8ec73166a33a266046bec2906f4b4aa
